version: "3.9"

services:
  app:
    container_name: scheduld
    build:
      context: ./..
      dockerfile: deployments/Dockerfile
    env_file:
      - ../configs/configs.env
    ports:
      - ${APPLICATION_PORT:-8080}:8080
    networks:
      - network
    restart: always
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chats_settings
    volumes:
      - ../assets/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
    restart: always

  adminer:
      image: adminer
      container_name: api-adminer
      restart: always
      ports:
        - ${ADMINER_PORT:-17860}:8080
      networks:
        - network
      depends_on:
        - postgres

networks:
    network:
      driver: bridge
